service: aws-node-http-api-typescript-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x

package:
  individually: true

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
